field: 5d57c626-5e4b-47bd-8fea-7f0b9c1dcc79 # Regular giving amount boxes
fieldLayouts:
  70781bf9-372f-4274-957f-2b1666606c88:
    tabs:
      -
        elements:
          -
            fieldUid: 58e6b000-f6fa-4f8e-b3b7-fb3c49c5159c # Amount box
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  58e6b000-f6fa-4f8e-b3b7-fb3c49c5159c: # Amount box
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: amountBox
    instructions: ''
    name: 'Amount box'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 9e96b439-8999-4bec-9e4d-dd45d1c62ee0 # Amount
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a36e8e45-94b4-44f3-8a50-fedca2809c87 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_44_amountbox}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: amountBox
name: 'Amount boxes'
sortOrder: 1
