field: 338657ca-939e-46d8-bbea-9ca984fb7a9f # Cards
fieldLayouts:
  bd3d2aca-d06d-46c8-93a0-7bbef010ae22:
    tabs:
      -
        elements:
          -
            fieldUid: 8ac944b2-2dd7-488d-983d-9feb5b3cc7a3 # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18aad2d2-1a31-4834-964f-00413bc6d5ed # Header text icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4881baab-fb5a-4f28-8db5-8b0750a56b7d # Card items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8ac944b2-2dd7-488d-983d-9feb5b3cc7a3: # Header
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: ''
    name: Header
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  18aad2d2-1a31-4834-964f-00413bc6d5ed: # Header text icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headerTextIcon
    instructions: ''
    name: 'Header text icon'
    searchable: true
    settings:
      columnType: text
      iconSets: '*'
      remoteSets: '*'
      showLabels: ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
  4881baab-fb5a-4f28-8db5-8b0750a56b7d: # Card items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardItem
    instructions: ''
    name: 'Card items'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 6c4c11ac-021e-45b3-a9e6-baa58884d18e # Card title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 18548933-6264-4903-9f75-516ace8330cc # Card image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7188fe22-f189-4e55-83bf-6d6625882a40 # Card image zoom
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7f93d305-4d2c-44ce-a430-19de42f60e40 # Card body
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - ee68d96e-771f-4baf-977c-bfc7f92db7e6 # Card button title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - d27bf05b-0c8d-4ee5-ae8b-a7ee0c032cda # Card button link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4ddbcff3-fc20-403c-a1be-a24b71677cfc # Card button icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - bf7afc56-e5af-42cc-bfd0-f51cd506df6c # Hide card
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_carditem}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a card item'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: cardRow
name: 'Row with cards'
sortOrder: 1
