field: 3d10d985-092b-4e66-976f-b2ef9a74e210 # Section row
fieldLayouts:
  e25d6cae-caca-409d-b177-681ff8e13ede:
    tabs:
      -
        elements:
          -
            fieldUid: aa6d601e-e6d9-482e-82dc-c5e69202ddda # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4773fd30-c977-49ed-8659-8b002c7f3aa1 # Card with image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4773fd30-c977-49ed-8659-8b002c7f3aa1: # Card with image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardsWithImage
    instructions: ''
    name: 'Card with image'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - a1b4a8eb-c8fc-4b44-8bab-91f71bf4c0b7 # title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7e327019-ae4f-4f33-b61a-e8ef6f66e1ba # text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a6aa3016-e379-4266-84c0-53ea4611cb21 # Image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0192c06e-eae9-4ce0-8c7a-a24a440b74e1 # Link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b94f815e-58cb-4f8e-aad7-0d786e713536 # Link text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_37_cardswithimage}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a card'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  aa6d601e-e6d9-482e-82dc-c5e69202ddda: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cards
name: 'Cards with image'
sortOrder: 4
