field: bed12be0-0179-43c6-aa65-229af2fa492d # Impact 
fieldLayouts:
  f628be7a-f286-4fab-bc1e-100fe7e9771c:
    tabs:
      -
        elements:
          -
            fieldUid: ce6ca13e-68d0-4780-b4d3-bedf50013650 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7464e80-e294-4638-a910-139a3a9dd3a1 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 260b6840-51d2-4b3d-9149-55b2c3f01063 # Card with image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  260b6840-51d2-4b3d-9149-55b2c3f01063: # Card with image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardWithImage
    instructions: ''
    name: 'Card with image'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - a4caff25-2f85-49ca-b546-6161a9ccc697 # Card title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c6b71ecc-c878-4a05-a409-148f9f7ba9e8 # Card text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 704aa0c7-fd5b-419d-aa0c-99cc36d1c5b4 # Card image
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0e7fc0ff-823f-4982-bad9-2b319671cab3 # Card link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 078fd993-19cb-43a5-804a-0c1240240d51 # Card link text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_50_cardwithimage}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  c7464e80-e294-4638-a910-139a3a9dd3a1: # Subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ce6ca13e-68d0-4780-b4d3-bedf50013650: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: cards
name: 'Cards with image'
sortOrder: 3
