field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9 # Content block
fieldLayouts:
  d4f9c486-7867-4dd1-97bc-dcce99542d77:
    tabs:
      -
        elements:
          -
            fieldUid: e47d7e3f-80be-44fe-8022-0d8ac03d0d57 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 794e5528-8ada-4fcc-8d67-ee3fb58905e1 # Subline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b5ba5b41-4bd5-4984-8982-1a80317498ca # Download
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 02a0696b-5fef-4116-ba52-f18b14fe7009 # Color style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  02a0696b-5fef-4116-ba52-f18b14fe7009: # Color style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: colorStyle
    instructions: 'Choose from below to use different background colour and text style for the block'
    name: 'Color style'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  794e5528-8ada-4fcc-8d67-ee3fb58905e1: # Subline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subline
    instructions: 'small amount of text to appear under heading if required - use for short explanations'
    name: Subline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b5ba5b41-4bd5-4984-8982-1a80317498ca: # Download
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: download
    instructions: ''
    name: Download
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24' # Documents
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Choose a file to add'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24' # Documents
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e47d7e3f-80be-44fe-8022-0d8ac03d0d57: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'heading to show above download(s)'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: downloads
name: Downloads
sortOrder: 6
