field: fd894e73-ca1e-4682-8abd-242d8fb30a84 # Email Content block
fieldLayouts:
  6abf7420-9f5c-4334-8b16-2edd1294db1c:
    tabs:
      -
        elements:
          -
            fieldUid: 5645815c-875c-45ad-93ef-bb64cfa54b79 # emailEntry
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 37fbe689-882e-44f0-9c7e-fe4d2dc9b453 # Button text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  37fbe689-882e-44f0-9c7e-fe4d2dc9b453: # Button text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5645815c-875c-45ad-93ef-bb64cfa54b79: # emailEntry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: emailentry
    instructions: ''
    name: emailEntry
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add an existing entry to the email'
      showSiteMenu: true
      source: null
      sources:
        - 'section:de4daed0-91e0-4d82-95d3-14e27ea0b01c' # News
        - 'section:projects'
        - 'section:ship'
        - 'section:sponsors'
        - 'section:22867151-2300-450d-ad2b-104bf8ae2fc0' # Staff
        - 'section:stories'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: emailFromEntry
name: 'Email from entry'
sortOrder: 2
