field: fd894e73-ca1e-4682-8abd-242d8fb30a84 # Email Content block
fieldLayouts:
  34d3707f-bc6d-42fc-9d03-b31f51775edc:
    tabs:
      -
        elements:
          -
            fieldUid: 164b0350-c395-4f68-86bd-c0a84cbf50bb # Block heading
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dcab0869-0f43-4fb4-973e-26062eaa1dca # Block Body
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4595a499-a04e-4e0f-9f94-da03541a10a2 # Block image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2c2d3082-8f2d-4878-8259-6e8b3d7c65ed # contentDate
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27bb9a81-6849-4f8b-8166-e3813c2460dc # Block image width
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: de94e283-7bbd-4f83-bdd7-9e4da969576b # Button link
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84cc2d7f-6073-412b-9f3b-c00e8233c195 # Button text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2c2d3082-8f2d-4878-8259-6e8b3d7c65ed: # contentDate
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: blockContentdate
    instructions: ''
    name: contentDate
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: true
      showTime: false
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  27bb9a81-6849-4f8b-8166-e3813c2460dc: # Block image width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockImageWidth
    instructions: ''
    name: 'Block image width'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 100%
            -
              - value
              - '100'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 50%
            -
              - value
              - '50'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  84cc2d7f-6073-412b-9f3b-c00e8233c195: # Button text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  164b0350-c395-4f68-86bd-c0a84cbf50bb: # Block heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockHeading
    instructions: ''
    name: 'Block heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4595a499-a04e-4e0f-9f94-da03541a10a2: # Block image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blockimage
    instructions: ''
    name: 'Block image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dcab0869-0f43-4fb4-973e-26062eaa1dca: # Block Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: blockBody
    instructions: ''
    name: 'Block Body'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  de94e283-7bbd-4f83-bdd7-9e4da969576b: # Button link
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: 'Add a link for read more button'
    name: 'Button link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: emailCustomContent
name: 'Email custom content'
sortOrder: 1
