field: fd894e73-ca1e-4682-8abd-242d8fb30a84
fieldLayouts:
  34d3707f-bc6d-42fc-9d03-b31f51775edc:
    tabs:
      -
        fields:
          164b0350-c395-4f68-86bd-c0a84cbf50bb:
            required: false
            sortOrder: 1
          27bb9a81-6849-4f8b-8166-e3813c2460dc:
            required: false
            sortOrder: 5
          2c2d3082-8f2d-4878-8259-6e8b3d7c65ed:
            required: false
            sortOrder: 4
          4595a499-a04e-4e0f-9f94-da03541a10a2:
            required: false
            sortOrder: 3
          84cc2d7f-6073-412b-9f3b-c00e8233c195:
            required: false
            sortOrder: 7
          dcab0869-0f43-4fb4-973e-26062eaa1dca:
            required: false
            sortOrder: 2
          de94e283-7bbd-4f83-bdd7-9e4da969576b:
            required: false
            sortOrder: 6
        name: Content
        sortOrder: 1
fields:
  164b0350-c395-4f68-86bd-c0a84cbf50bb:
    contentColumnType: text
    fieldGroup: null
    handle: blockHeading
    instructions: ''
    name: 'Block heading'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  27bb9a81-6849-4f8b-8166-e3813c2460dc:
    contentColumnType: string
    fieldGroup: null
    handle: blockImageWidth
    instructions: ''
    name: 'Block image width'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 100%
            -
              - value
              - '100'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 50%
            -
              - value
              - '50'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  2c2d3082-8f2d-4878-8259-6e8b3d7c65ed:
    contentColumnType: datetime
    fieldGroup: null
    handle: blockContentdate
    instructions: ''
    name: contentDate
    searchable: true
    settings:
      minuteIncrement: '30'
      showDate: true
      showTime: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  4595a499-a04e-4e0f-9f94-da03541a10a2:
    contentColumnType: string
    fieldGroup: null
    handle: blockimage
    instructions: ''
    name: 'Block image'
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: ''
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  84cc2d7f-6073-412b-9f3b-c00e8233c195:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dcab0869-0f43-4fb4-973e-26062eaa1dca:
    contentColumnType: text
    fieldGroup: null
    handle: blockBody
    instructions: ''
    name: 'Block Body'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  de94e283-7bbd-4f83-bdd7-9e4da969576b:
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: 'Add a link for read more button'
    name: 'Button link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: emailCustomContent
name: 'Email custom content'
sortOrder: 1
