field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9 # Content block
fieldLayouts:
  1cec3fe1-ad4b-416b-975b-1da17f4dae15:
    tabs:
      -
        elements:
          -
            fieldUid: 156a5bc1-a9cb-41f6-b3a1-6d0a2497dc2e # Embed code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cbea64af-c1ed-4e57-9176-efd0a03ab710 # Background color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  156a5bc1-a9cb-41f6-b3a1-6d0a2497dc2e: # Embed code
    columnSuffix: uurscccq
    contentColumnType: text
    fieldGroup: null
    handle: embedCode
    instructions: 'Past embed code in here'
    name: 'Embed code'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '10'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cbea64af-c1ed-4e57-9176-efd0a03ab710: # Background color
    columnSuffix: humnlsmr
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: ''
    name: 'Background color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Gray
            -
              - value
              - bg-gray
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: embed
name: Embed
sortOrder: 9
