field: 3d10d985-092b-4e66-976f-b2ef9a74e210
fieldLayouts:
  a8c5e247-93bf-4ddc-aa68-334f563f6e29:
    tabs:
      -
        elements:
          -
            fieldUid: 7ece6dd1-43a7-43e2-954d-618c49371c0d
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 489f013c-c054-4552-b965-94911c2bae90
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7cc9469f-f82a-4189-9666-cf37ac075b86
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8667f163-2e8c-4ba4-b519-f5dd8699a955
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  489f013c-c054-4552-b965-94911c2bae90:
    contentColumnType: string
    fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec
    handle: icons
    instructions: ''
    name: Icons
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - 08a7e56e-2483-4fe2-a651-649f8423c463
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 363cf021-aee1-4c33-a240-4cee24ffc96a
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a8fb4007-f9b2-4386-8444-4c3f8e561b86
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - c376e0b9-b7ff-43d9-90b3-708f9e817bf2
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f55508fe-d5c8-43dc-b831-c7369df9e8f7
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_icons_3}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add icon column'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  7cc9469f-f82a-4189-9666-cf37ac075b86:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7ece6dd1-43a7-43e2-954d-618c49371c0d:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8667f163-2e8c-4ba4-b519-f5dd8699a955:
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: iconRow
name: 'Icon row'
sortOrder: 1
