field: df4c702a-094d-4113-85c5-a6b7f23f88a0 # Impact stats
fieldLayouts:
  0a9e7cd8-e80f-4b55-91a8-148f44ebea6d:
    tabs:
      -
        elements:
          -
            fieldUid: 85ebfc65-5359-45f9-9431-39628606a852 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: be2d090c-b7de-43dc-915b-194dc8de3e34 # Impact card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  85ebfc65-5359-45f9-9431-39628606a852: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Heading for impact stats'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be2d090c-b7de-43dc-915b-194dc8de3e34: # Impact card
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: impactCard
    instructions: ''
    name: 'Impact card'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - bf1ee760-333d-462e-a0ad-1a014c2c9538 # Icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 06085e59-ce31-4870-a7e3-e32b6f3aad17 # Stat
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 09dce948-15fb-4b5d-818c-a1e33e6cdb15 # Statistic type
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 9c8ca7e8-254f-441a-8bc8-6b48a21039eb # Impact text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_32_impactcard}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a statistic card'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: impact
name: Impact
sortOrder: 1
