field: 7382c89d-f041-4b2a-a12b-1b73543ff4fc
fieldLayouts:
  2c0b105e-1987-4aa0-9832-9ebfaf82c16a:
    tabs:
      -
        elements:
          -
            fieldUid: a268689a-b894-4ddb-8200-46872f2cb71d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e9995c0-eaab-4dbc-b6d0-1a5b92d5e7b2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2e9995c0-eaab-4dbc-b6d0-1a5b92d5e7b2:
    contentColumnType: string
    fieldGroup: null
    handle: impactCard
    instructions: ''
    name: 'Impact card'
    searchable: false
    settings:
      contentTable: '{{%stc_impactcard}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a268689a-b894-4ddb-8200-46872f2cb71d:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Heading for impact stats'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: impact
name: Impact
sortOrder: 3
