field: 7382c89d-f041-4b2a-a12b-1b73543ff4fc # Project content
fieldLayouts:
  2c0b105e-1987-4aa0-9832-9ebfaf82c16a:
    tabs:
      -
        elements:
          -
            fieldUid: a268689a-b894-4ddb-8200-46872f2cb71d # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e9995c0-eaab-4dbc-b6d0-1a5b92d5e7b2 # Impact card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2e9995c0-eaab-4dbc-b6d0-1a5b92d5e7b2: # Impact card
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: impactCard
    instructions: ''
    name: 'Impact card'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - ca158746-21d0-492a-848b-8165c4a69b2f # Icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 07f10331-5743-426a-b68c-5150c2e37921 # Stat
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b3e391ba-03c4-4001-90be-acf672dcc7e9 # Statistic type
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b7361645-8d0c-4836-8cc3-e91a8c78d0ab # Impact text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_34_impactcard}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a268689a-b894-4ddb-8200-46872f2cb71d: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Heading for impact stats'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: impact
name: Impact
sortOrder: 3
