field: 3d10d985-092b-4e66-976f-b2ef9a74e210 # Section row
fieldLayouts:
  2d515175-ab05-47c5-820e-ab01ab3a6dc6:
    tabs:
      -
        elements:
          -
            fieldUid: b0201f60-1c50-4fab-828e-31ffbec51ceb # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6dfe161d-1e03-4c3c-89f8-cd7fc90866ab # News items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6dfe161d-1e03-4c3c-89f8-cd7fc90866ab: # News items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: newsItems
    instructions: 'Add three news items for auto inclusion'
    name: 'News items'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '3'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:de4daed0-91e0-4d82-95d3-14e27ea0b01c' # News
      targetSiteId: null
      validateRelatedElements: true
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b0201f60-1c50-4fab-828e-31ffbec51ceb: # Heading
    columnSuffix: vudstywg
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: newsRow
name: 'News row'
sortOrder: 7
