field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9
fieldLayouts:
  4ae26920-742a-4e6d-9b02-e938c7cc4a42:
    tabs:
      -
        fields:
          0c1c29aa-3066-417e-a569-3b8ad4b2ccbf:
            required: false
            sortOrder: 1
          213c5cea-e8c3-48a5-9501-d506030864dd:
            required: false
            sortOrder: 2
          29a1fb65-d50c-4f48-8297-164038ba941a:
            required: false
            sortOrder: 4
          7fb40023-ad56-4c67-bc65-9353674d5c1b:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  0c1c29aa-3066-417e-a569-3b8ad4b2ccbf:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  213c5cea-e8c3-48a5-9501-d506030864dd:
    contentColumnType: text
    fieldGroup: null
    handle: citationIntro
    instructions: ''
    name: 'Citation intro'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  29a1fb65-d50c-4f48-8297-164038ba941a:
    contentColumnType: string(255)
    fieldGroup: null
    handle: citationLink
    instructions: 'Add a link if relevant to the source'
    name: 'Citation link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  7fb40023-ad56-4c67-bc65-9353674d5c1b:
    contentColumnType: text
    fieldGroup: null
    handle: citation
    instructions: ''
    name: Citation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 4
