field: bed12be0-0179-43c6-aa65-229af2fa492d # Impact 
fieldLayouts:
  b37e7c8b-6cec-43bb-a80e-5785e83ce9bd:
    tabs:
      -
        elements:
          -
            fieldUid: ab909092-3ebe-4c5c-bd0d-277f01e1cd79 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 388aac61-d66c-4310-b77f-3c208ae044d2 # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  388aac61-d66c-4310-b77f-3c208ae044d2: # Quote
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 30d37422-65da-4834-9c34-09dfa288b27a # Quote
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b3bb00b6-db87-423a-81f0-8d1197a68b96 # Source
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1f00d7e3-9605-49bb-bdbe-f2d330b29afd # Citation
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_51_quote}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  ab909092-3ebe-4c5c-bd0d-277f01e1cd79: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: optional
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 4
