field: 3d10d985-092b-4e66-976f-b2ef9a74e210
fieldLayouts:
  c691d312-670a-42ff-a51d-18efa8300f4f:
    tabs:
      -
        fields:
          0c3a5864-4f6e-4b09-b5f7-a9b69186fdba:
            required: false
            sortOrder: 7
          308decac-4286-44f8-a527-be398712fb28:
            required: false
            sortOrder: 5
          50767b65-0c59-40a9-8c99-8406a218547d:
            required: false
            sortOrder: 1
          7f5bb829-fcc7-4802-bd98-9e1f08a068c7:
            required: false
            sortOrder: 3
          acc4ebee-da79-4b1a-b90e-eb9aea923bc8:
            required: false
            sortOrder: 6
          cca92393-d501-4345-b5b7-901c5473ffcc:
            required: false
            sortOrder: 2
          ebc6a877-8871-49ba-b579-66310f99ae02:
            required: false
            sortOrder: 4
          f7610447-3781-467d-bbaf-c1741bff66ac:
            required: false
            sortOrder: 8
        name: Content
        sortOrder: 1
fields:
  0c3a5864-4f6e-4b09-b5f7-a9b69186fdba:
    contentColumnType: text
    fieldGroup: null
    handle: author
    instructions: ''
    name: Author
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  308decac-4286-44f8-a527-be398712fb28:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  50767b65-0c59-40a9-8c99-8406a218547d:
    contentColumnType: text
    fieldGroup: null
    handle: contentType
    instructions: ''
    name: 'Content type'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7f5bb829-fcc7-4802-bd98-9e1f08a068c7:
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: ''
    name: Intro
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  acc4ebee-da79-4b1a-b90e-eb9aea923bc8:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cca92393-d501-4345-b5b7-901c5473ffcc:
    contentColumnType: text
    fieldGroup: null
    handle: rowTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ebc6a877-8871-49ba-b579-66310f99ae02:
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      limit: ''
      localizeRelations: false
      selectionLabel: 'Link to an entry'
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  f7610447-3781-467d-bbaf-c1741bff66ac:
    contentColumnType: text
    fieldGroup: null
    handle: authorRole
    instructions: ''
    name: 'Author role'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quoteRow
name: 'Quote row'
sortOrder: 2
