field: 027841ee-12c9-4ec8-93a1-6ce221dc5175
fieldLayouts:
  64c8b5fd-4e9c-48ba-a37c-6bada30ec248:
    tabs:
      -
        elements:
          -
            fieldUid: bd4fdb0c-a16e-4eaf-abe7-bf26e2c107d3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e4f2ec4-9a04-49e3-ab87-c91d8c242154
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bcadc3a3-87e2-4ed5-8068-f309505031be
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aa29a687-6bad-4bf2-a98e-2c6c3cb598b1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7e4f2ec4-9a04-49e3-ab87-c91d8c242154:
    contentColumnType: string
    fieldGroup: null
    handle: download
    instructions: 'Add from downloads or upload and select file required '
    name: Download
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds: null
      defaultUploadLocationSource: 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add a referral document for download'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  aa29a687-6bad-4bf2-a98e-2c6c3cb598b1:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: 'Text to appear on download button'
    name: 'Button text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bcadc3a3-87e2-4ed5-8068-f309505031be:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bd4fdb0c-a16e-4eaf-abe7-bf26e2c107d3:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: referralBlock
name: 'Referral block'
sortOrder: 1
