field: d9918bb6-9a7e-43aa-b619-9c3b1aa7ce4c
fieldLayouts:
  5d77f907-18f3-405c-aa3f-7a77cd7d1d0e:
    tabs:
      -
        fields:
          2c35d7b7-13ba-414f-993b-5467b5339c44:
            required: false
            sortOrder: 1
          5ff0093e-adfd-4381-a086-b53343bc7332:
            required: false
            sortOrder: 2
          63f6b683-8dd1-4efd-9a56-5a97a7000eaf:
            required: false
            sortOrder: 3
          6d85c2e9-42bb-4f4f-90be-8df5a2701776:
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
fields:
  2c35d7b7-13ba-414f-993b-5467b5339c44:
    contentColumnType: string
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Centre
            -
              - value
              - centre
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  5ff0093e-adfd-4381-a086-b53343bc7332:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  63f6b683-8dd1-4efd-9a56-5a97a7000eaf:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowedKinds: null
      defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: ''
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
        - 'volume:ddf55caf-7ee2-4e28-a3a7-5403cb88782e'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6d85c2e9-42bb-4f4f-90be-8df5a2701776:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: rowImage
name: 'Image row'
sortOrder: 2
