field: d9918bb6-9a7e-43aa-b619-9c3b1aa7ce4c
fieldLayouts:
  7a27a594-aa57-4325-8f8c-41c467776234:
    tabs:
      -
        fields:
          0865e992-6a27-4f47-92c3-8716a6c0bdb6:
            required: false
            sortOrder: 1
          671b8666-c5d7-4c0d-9b0a-d0d61ce5f9c9:
            required: false
            sortOrder: 2
          9dffc050-eeec-4a4f-a5fd-fdbc228a980a:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  0865e992-6a27-4f47-92c3-8716a6c0bdb6:
    contentColumnType: string
    fieldGroup: null
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Centre
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  671b8666-c5d7-4c0d-9b0a-d0d61ce5f9c9:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9dffc050-eeec-4a4f-a5fd-fdbc228a980a:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: rowText
name: 'Text only row'
sortOrder: 1
