field: 46534cc6-293f-4afe-a72c-ea06b8200e30 # Hero carousel settings
fieldLayouts:
  2e0cf2ac-20f5-4391-89b6-ba7e6da970de:
    tabs:
      -
        elements:
          -
            fieldUid: f623b4ae-6e3f-49f3-9fe2-629cf2ba5b9b # Tabs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 23d78b60-aad6-4927-9e9d-824ebd95de7c # Autoplay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2aeb59bf-4aea-42a8-a8e2-37164ba667af # Arrows
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2aeb59bf-4aea-42a8-a8e2-37164ba667af: # Arrows
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: arrows
    instructions: 'Show arrows'
    name: Arrows
    searchable: false
    settings:
      default: true
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  23d78b60-aad6-4927-9e9d-824ebd95de7c: # Autoplay
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: 'Should slides automatically play'
    name: Autoplay
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  f623b4ae-6e3f-49f3-9fe2-629cf2ba5b9b: # Tabs
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: tabs
    instructions: 'Shows or hides the tab navigation underneath slides'
    name: Tabs
    searchable: false
    settings:
      default: false
      offLabel: 'Hide tabs'
      onLabel: 'Show tabs'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: settings
name: Settings
sortOrder: 1
