field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9 # Content block
fieldLayouts:
  c2b61014-5030-45ab-bcdc-de7ee025b0cb:
    tabs:
      -
        elements:
          -
            fieldUid: 434bfc8b-0381-4f32-9b10-9a7f34e55b59 # Include share links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  434bfc8b-0381-4f32-9b10-9a7f34e55b59: # Include share links
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: includeShareLinks
    instructions: 'Turn on to add a row of share links for FB,Twitter and LinkedIn (Instagram has no share service)'
    name: 'Include share links'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: shareRow
name: 'Share row'
sortOrder: 8
