field: 9abbaee7-cb0e-4e11-b58f-88ba10242b3b # Hero Carousel
fieldLayouts:
  e9526af7-5d0b-41a5-afbd-c535148b724e:
    tabs:
      -
        elements:
          -
            fieldUid: 1f3e832f-50bb-4ce8-b8c1-bf85468f60ab # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb1452df-3ceb-4b35-a22e-70da941ee2ed # Pre-title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ba48dc9-f0b4-4494-8c36-4c201f29d30e # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0437e674-d59b-4a77-b218-bc93e9bf6a98 # Title size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 24b01e2c-5b81-4a15-bdf0-2e7f3c86f059 # Title text align
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f02681ca-0e3d-4e81-8d29-7f32bffcd4b2 # Text color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b21ef471-656c-4603-9c53-ca272b6a5680 # Main text position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3a4e2b4d-08b2-4f63-8299-5c38c319a03a # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7e91359-b687-40b7-97c3-954dcb9e416d # Button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41ffb4a1-9c5d-492d-be3a-bd7d27a2a4b1 # Button link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bfdad300-d7bd-4ee6-9a0a-9b17f290226c # Tab title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 3f74b20e-10d0-4f46-87fb-25591318bab6 # Tab icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  1f3e832f-50bb-4ce8-b8c1-bf85468f60ab: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add slide image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  3a4e2b4d-08b2-4f63-8299-5c38c319a03a: # Intro
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: intro
    instructions: 'probably not necessary so may remove this field!'
    name: Intro
    searchable: true
    settings:
      byteLimit: null
      charLimit: 160
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3f74b20e-10d0-4f46-87fb-25591318bab6: # Tab icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tabIcon
    instructions: 'Select an image to use as an icon on the text tab under the slider'
    name: 'Tab icon'
    searchable: false
    settings:
      columnType: text
      iconSets:
        - 'font:themify--fvbane.woff'
      remoteSets: ''
      showLabels: ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
  9ba48dc9-f0b4-4494-8c36-4c201f29d30e: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  24b01e2c-5b81-4a15-bdf0-2e7f3c86f059: # Title text align
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: titleTextAlign
    instructions: ''
    name: 'Title text align'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Text left'
            -
              - value
              - text-left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Text center'
            -
              - value
              - text-center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Text right'
            -
              - value
              - text-right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  41ffb4a1-9c5d-492d-be3a-bd7d27a2a4b1: # Button link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: 'Leave blank to hide'
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  0437e674-d59b-4a77-b218-bc93e9bf6a98: # Title size
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: titleSize
    instructions: 'Use this to adjust title size - longer titles might need smaller text and positioning on the image'
    name: 'Title size'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - large
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - medium
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - small
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a7e91359-b687-40b7-97c3-954dcb9e416d: # Button text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: 'Leave blank to hide'
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b21ef471-656c-4603-9c53-ca272b6a5680: # Main text position
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: 'select a placement for the text box over the image'
    name: 'Main text position'
    searchable: false
    settings:
      default: right
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - '1'
          -
            - drop-right
            - '1'
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  bb1452df-3ceb-4b35-a22e-70da941ee2ed: # Pre-title
    columnSuffix: null
    contentColumnType: string(200)
    fieldGroup: null
    handle: preTitle
    instructions: 'Small snippet before large title text'
    name: Pre-title
    searchable: false
    settings:
      byteLimit: null
      charLimit: 50
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bfdad300-d7bd-4ee6-9a0a-9b17f290226c: # Tab title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tabTitle
    instructions: 'Text to display in navigation tab under each slide'
    name: 'Tab title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f02681ca-0e3d-4e81-8d29-7f32bffcd4b2: # Text color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: textColor
    instructions: ''
    name: 'Text color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - black
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: slide
name: Slide
sortOrder: 1
