field: 1554467f-ed0f-4d53-9852-9ca771d47e2c # Feature split lines
fieldLayouts:
  ad44495e-27a2-48ce-8310-c068875debdc:
    tabs:
      -
        elements:
          -
            fieldUid: 62cc6b1f-04f6-4075-8e6c-eea573ce8d0b # Split Line
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  62cc6b1f-04f6-4075-8e6c-eea573ce8d0b: # Split Line
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: splitLine
    instructions: ''
    name: 'Split Line'
    searchable: false
    settings:
      contentTable: '{{%stc_splitline}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: splitLines
name: 'Split lines'
sortOrder: 1
