field: 300d193f-c768-4945-8669-26af92cf0613
fieldLayouts:
  f05cfd7b-fdeb-440f-9367-f9229d801013:
    tabs:
      -
        fields:
          7889e0d3-a94d-47a2-ab7e-6d03aa0e33cf:
            required: false
            sortOrder: 2
          8b0672bb-de4e-4a90-a29b-cb2319ff0f45:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  7889e0d3-a94d-47a2-ab7e-6d03aa0e33cf:
    contentColumnType: datetime
    fieldGroup: null
    handle: sponsorshipEndDate
    instructions: ''
    name: 'Sponsorship end date'
    searchable: true
    settings:
      minuteIncrement: '30'
      showDate: true
      showTime: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  8b0672bb-de4e-4a90-a29b-cb2319ff0f45:
    contentColumnType: string
    fieldGroup: null
    handle: sponsoredby
    instructions: ''
    name: Sponsoredby
    searchable: true
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources:
        - 'section:sponsors'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: sponsored
name: Sponsored
sortOrder: 1
