field: bed12be0-0179-43c6-aa65-229af2fa492d # Impact 
fieldLayouts:
  9e58f28d-f0e1-412f-9a4a-6d0da7337db9:
    tabs:
      -
        elements:
          -
            fieldUid: 3304054c-fdbb-4d94-a6d8-c3dc235d14e9 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 236c71d3-e245-44aa-97de-e573ab448fa3 # subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f9319ae-1f11-46d3-9583-bc10fba15291 # Stat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7f9319ae-1f11-46d3-9583-bc10fba15291: # Stat
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: stat
    instructions: ''
    name: Stat
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - f6eb9d8b-9521-4dcc-abbe-2ca820acd962 # Icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 291ce790-b12a-4a1f-8dc5-28adcc651ae9 # text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b70052cf-a8da-4fdd-8bc3-e283d5a27d1e # Icon color
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 903170fb-f831-4048-85fd-6b7f31cd2dff # Icon size
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_49_stat}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  236c71d3-e245-44aa-97de-e573ab448fa3: # subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3304054c-fdbb-4d94-a6d8-c3dc235d14e9: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: stats
name: Stats
sortOrder: 2
