field: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9
fieldLayouts:
  8efae287-b2a5-469d-acc1-8b33c8126af8:
    tabs:
      -
        fields:
          e6566bbe-eaf3-4424-9f1c-3df84eeed2ef:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  e6566bbe-eaf3-4424-9f1c-3df84eeed2ef:
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: 'Add your embed code here'
    name: Video
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '6'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: video
name: Video
sortOrder: 3
