field: 7382c89d-f041-4b2a-a12b-1b73543ff4fc # Project content
fieldLayouts:
  82551814-2ee2-482f-bb51-1d807ad57cd3:
    tabs:
      -
        elements:
          -
            fieldUid: e041ec6e-fc69-4419-87e4-a9613ba87b5c # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e041ec6e-fc69-4419-87e4-a9613ba87b5c: # Video
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: video
    instructions: ''
    name: Video
    searchable: false
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
handle: video
name: Video
sortOrder: 5
