fieldLayouts:
  85906a39-237d-41aa-99a0-a984c00e4ad5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 85fc3b41-3642-41bd-a769-2cf9e1b27ccd # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Default
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 40e8c726-41e0-4aa7-aab2-2b9bda75957d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: basic
hasTitleField: true
name: Basic
section: d92c03cb-0d89-4034-a675-4c44d44df257 # Pages
sortOrder: 10
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
