fieldLayouts:
  85906a39-237d-41aa-99a0-a984c00e4ad5:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 85fc3b41-3642-41bd-a769-2cf9e1b27ccd
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Default
        sortOrder: 1
handle: basic
hasTitleField: true
name: Basic
section: d92c03cb-0d89-4034-a675-4c44d44df257
sortOrder: 10
titleFormat: ''
