fieldLayouts:
  6cabe1ca-48d2-4b68-9913-fd8a38473bd5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 14edf059-6ee9-43fb-83b3-2ad7ba50b48e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 328cc8da-7631-4985-b34f-a1c071efe5f2 # Campaign name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 98b30784-0bde-4938-928a-6bf154a806a9 # Intro text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 85fc3b41-3642-41bd-a769-2cf9e1b27ccd # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b98253b-ff78-4531-b512-936251f733b6 # PDF document
            instructions: ''
            label: Infographic
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99c5fcee-86df-44ab-932b-3f4cc2609a23 # PDF Thumbnail image
            instructions: ''
            label: 'Infographic thumb'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f3938584-5744-4277-89ef-45f37006fbbf # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c459dbbc-2bb1-412a-b519-6b7df470d58b # Campaign box text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 701a50af-8940-4aa8-9ad6-d78870a1a053 # Donate button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0089a26-45cd-4af0-a9f2-5f78694a585c # CTA custom link
            instructions: ''
            label: 'Donate link'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 40e8c726-41e0-4aa7-aab2-2b9bda75957d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: campaignStories
hasTitleField: true
name: 'Campaign Stories'
section: 79c0e951-9d0b-4feb-8b83-77c2c61732da # Campaign Stories
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
