fieldLayouts:
  dcfad19d-7c35-4b08-bd2f-53085fe0a11b:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 98b30784-0bde-4938-928a-6bf154a806a9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 85fc3b41-3642-41bd-a769-2cf9e1b27ccd
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4fbb28d9-5f55-47db-b772-301d46321c7c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Join
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4fe18d87-a2d3-4236-b953-a5608e77a2f0
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f46fe5e9-2526-455d-8d3f-7c04730555cb
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Mobile specific'
        sortOrder: 2
handle: joinpage
hasTitleField: true
name: 'Join page'
section: d92c03cb-0d89-4034-a675-4c44d44df257
sortOrder: 8
titleFormat: null
