fieldLayouts:
  9d1d8361-b01f-47ef-8856-08b179cf4ffd:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 98b30784-0bde-4938-928a-6bf154a806a9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 338657ca-939e-46d8-bbea-9ca984fb7a9f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cf1e4563-c3fa-4515-bc6c-0a8d7d25980f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: abaa395c-662b-4f31-932b-edc406a82c5c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Landing page 1'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 727edbaa-4674-4a82-bc49-28a722425891
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1eba2c3a-5fac-49e8-b41a-4d750a8e9439
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Banner
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 40e8c726-41e0-4aa7-aab2-2b9bda75957d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 3
handle: landingPage1
hasTitleField: true
name: 'Landing page 1'
section: d92c03cb-0d89-4034-a675-4c44d44df257
sortOrder: 2
titleFormat: ''
