fieldLayouts:
  45a9c8c4-4724-447d-be2f-2a424e02972f:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 943d62c7-9600-469f-b6d7-9f8162759193
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 70579a5e-bdbd-4298-a851-a0f6979cc7a1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cf1e4563-c3fa-4515-bc6c-0a8d7d25980f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: abaa395c-662b-4f31-932b-edc406a82c5c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Menu
        sortOrder: 1
      -
        name: SEO
        sortOrder: 2
handle: mainMenu
hasTitleField: true
name: 'Main menu'
section: 8a7d22bc-7764-40d5-9fd6-df4752eb365e
sortOrder: 1
titleFormat: null
