fieldLayouts:
  666060eb-1e8f-4c6d-af08-f662f1e479a5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 08ae4aff-6488-4c53-affc-a1abd7b92a7f # Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 08d20686-3600-47f2-8c0a-9e17b8d80457 # Sticky
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 14edf059-6ee9-43fb-83b3-2ad7ba50b48e # Image
            instructions: 'Choose a large image - it will appear on main news listing and in article'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: a1fb593f-8cf1-4328-a410-8af0f7d0cbe6 # news intro
            instructions: 'Use this as the text to be shown in the news list display - it will not be shown on the news entry item view'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: acbc0bba-242f-40cf-bdd1-a6417f6eeaa9 # Content block
            instructions: 'Build your page by adding content blocks'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2639022-dbb4-4ea3-8e00-dbccac51844d # Location tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a6ae855d-6642-404c-9ad4-1b9608ee6a85 # Topic Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 40e8c726-41e0-4aa7-aab2-2b9bda75957d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: newsBlockBuilder
hasTitleField: true
name: 'News block builder'
section: de4daed0-91e0-4d82-95d3-14e27ea0b01c # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
