fieldLayouts:
  e219dee8-61dc-4100-8add-cc0bfe87c32e:
    tabs:
      -
        elements:
          -
            fieldUid: 3320a88b-3a20-4803-8c87-ce2a93ba9067 # Donate header image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: acc02c0a-e0f4-409f-9e64-8a1caad8f53b # Donate box information title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 969860b3-7deb-443b-8770-df252caa20d7 # Donate box intro text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc6722bc-176e-4111-964c-3f01d0fd0032 # Donate benefits item list
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bca8190-2f46-4e11-b1aa-565488535898 # Donate info box more text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Donate info box'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 031a35a5-fc17-4e4e-a861-2baf9bc970e1 # Donate form title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: efe1a4dc-c7b6-4fd4-8957-85e0c6453824 # Donate form subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 701a50af-8940-4aa8-9ad6-d78870a1a053 # Donate button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Form
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 40e8c726-41e0-4aa7-aab2-2b9bda75957d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: singleDonation
hasTitleField: true
name: 'Donation single'
section: aa98d899-2c21-48c4-be1e-a1154e9c2beb # Donation single
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
