fieldLayouts:
  8a4a3a81-357c-446c-a96f-ed77e681743c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: 'Staff name'
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 2d6cc6c6-6c70-4b25-9802-b040b9d12bfa
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 616cd910-0d50-4cdc-84c7-32169153b332
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 134d1fe5-ddc8-46d7-bb05-0291e4b5c260
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1b322709-69a0-45e5-a92d-b1e3adb27066
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e2639022-dbb4-4ea3-8e00-dbccac51844d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Staff
        sortOrder: 1
handle: staff
hasTitleField: true
name: Staff
section: 22867151-2300-450d-ad2b-104bf8ae2fc0
sortOrder: 1
titleFormat: ''
