fieldLayouts:
  8a4a3a81-357c-446c-a96f-ed77e681743c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: 'Staff name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 2d6cc6c6-6c70-4b25-9802-b040b9d12bfa # Staff image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 616cd910-0d50-4cdc-84c7-32169153b332 # Staff job title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 134d1fe5-ddc8-46d7-bb05-0291e4b5c260 # Staff team
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b322709-69a0-45e5-a92d-b1e3adb27066 # Staff biog
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2639022-dbb4-4ea3-8e00-dbccac51844d # Location tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Staff
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 40e8c726-41e0-4aa7-aab2-2b9bda75957d # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: staff
hasTitleField: true
name: Staff
section: 22867151-2300-450d-ad2b-104bf8ae2fc0 # Staff
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
