fieldLayouts:
  82dec387-25d1-45f8-a867-e4fcb466768d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 642977d9-c3cc-4eed-9b52-c111a413ab3f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3b9c3cb5-ac74-401a-a998-7dd9f31a8572
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Supports and funders'
        sortOrder: 1
handle: supportersFunders
hasTitleField: true
name: 'Supporters & Funders'
section: 98a49d1d-ea91-4fa4-97a1-3748fcec9423
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
