defaultPlacement: end
fieldLayouts:
  a7310cde-8cf6-403a-8b24-c0505f2a1e17:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: publications
name: Publications
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    hasUrls: true
    template: publications/_category
    uriFormat: 'our-work/publications/{slug}'
structure:
  maxLevels: null
  uid: c53f19e2-167f-46dd-b8bb-3bc997f4f656
