defaultPlacement: end
fieldLayouts:
  c6ba5d01-4e18-4d52-900e-fa8eff8e6fad:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: research
name: 'Research and policy'
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    hasUrls: true
    template: publications/_category
    uriFormat: 'our-work/research-and-policy/{slug}'
structure:
  maxLevels: null
  uid: fa1197d4-499c-4f34-9b40-dcea4aa587cc
