handle: staffGroups
name: 'Staff groups'
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    hasUrls: true
    template: ''
    uriFormat: 'staff-groups/{slug}'
structure:
  maxLevels: null
  uid: f53de9f5-b0b2-4a05-bf2a-8a39cafe552e
