fieldLayouts:
  fda2b218-631d-4e13-a149-b2207b6eda3a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: staffGroups
name: 'Staff groups'
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    hasUrls: true
    template: null
    uriFormat: 'staff-groups/{slug}'
structure:
  maxLevels: null
  uid: f53de9f5-b0b2-4a05-bf2a-8a39cafe552e
