fieldLayouts:
  6c5af70c-be71-4148-a7d2-82e0e49c78e3:
    tabs:
      -
        fields:
          2e999a83-5681-42a4-bf7d-99b2c00d47b3:
            required: false
            sortOrder: 2
          44ce4f57-f3d7-416c-bc55-f7505aa7b29e:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: bannerImages
hasUrls: true
name: 'Banner images'
settings:
  path: '@assetBasePath/images/banners/'
sortOrder: 5
type: craft\volumes\Local
url: '@assetBaseUrl/images/banners/'
