fieldLayouts:
  999d25e7-9182-4ad6-9f3d-5f3ae34b758c:
    tabs:
      -
        fields:
          2e999a83-5681-42a4-bf7d-99b2c00d47b3:
            required: false
            sortOrder: 2
          44ce4f57-f3d7-416c-bc55-f7505aa7b29e:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: oldNewsImages
hasUrls: true
name: 'Old news images'
settings:
  path: '@assetBasePath/images/oldblog'
sortOrder: 6
type: craft\volumes\Local
url: '@assetBaseUrl/images/oldblog'
