columnSuffix: null
contentColumnType: text
fieldGroup: 6f31baa9-2520-41f6-ab02-adf43db48203 # Global contact
handle: additionalContactInfo
instructions: 'Add short one liners with a <br> (shift return) as opposed to paragraph'
name: 'Additional contact info'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
