columnSuffix: null
contentColumnType: string
fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec # Banner
handle: backgroundBanner
instructions: ''
name: 'Background banner'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8efd0c0c-fba0-499f-a93e-1b57ff148494' # Banner images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
