columnSuffix: null
contentColumnType: text
fieldGroup: e001e685-5f71-409f-88bf-0a4c333d9520 # Default
handle: body
instructions: ''
name: Body
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: ''
  redactorConfig: Standard.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
