columnSuffix: null
contentColumnType: string
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f # Featured
handle: buttonPosition
instructions: 'If a link is required use this to position the button on the overlay'
name: 'Button position'
searchable: false
settings:
  default: ''
  options:
    __assoc__:
      -
        - left
        - ''
      -
        - center
        - '1'
      -
        - right
        - '1'
      -
        - full
        - ''
      -
        - drop-left
        - ''
      -
        - drop-right
        - '1'
translationKeyFormat: null
translationMethod: none
type: rias\positionfieldtype\fields\Position
