columnSuffix: null
contentColumnType: string
fieldGroup: e28a8bb8-82a0-4f13-a087-8b404ad4662c # Campaign
handle: campaignImage
instructions: 'Use a transparent campaign image to display in page'
name: 'Campaign image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:2297b6d5-b0fa-425f-bb4d-22b9658448ed' # Campaign images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:2297b6d5-b0fa-425f-bb4d-22b9658448ed' # Campaign images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
