columnSuffix: affguxxi
contentColumnType: text
fieldGroup: 04f271ca-91c2-45b8-a0a9-5510973cadcd # Pages
handle: contentFooter
instructions: 'If used this will appear at the foot of page content and above the footer'
name: 'Content footer'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
