columnSuffix: null
contentColumnType: string
fieldGroup: 57e17ebd-5a65-4486-a175-645b52fcf8e5 # Global site info
handle: cookiePage
instructions: 'Link to cookie page'
name: 'Cookie page'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
