contentColumnType: text
fieldGroup: 972163a3-4d75-4e5a-af88-88030b7a0689
handle: copyrightText
instructions: ''
name: 'Copyright text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
