contentColumnType: string
fieldGroup: f4c77426-3ec4-4532-b94d-83fff64f75c4
handle: ctaButtonColor
instructions: ''
name: 'CTA button color'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Red
        -
          - value
          - btn-primary
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Dark gray/black'
        -
          - value
          - btn-secondary
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Outline
        -
          - value
          - btn-outline
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Light
        -
          - value
          - btn-light
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
