columnSuffix: null
contentColumnType: string
fieldGroup: e001e685-5f71-409f-88bf-0a4c333d9520 # Default
handle: ctaBlock
instructions: ''
name: 'CTA block'
searchable: false
settings:
  contentTable: '{{%matrixcontent_ctablock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
