columnSuffix: null
contentColumnType: text
fieldGroup: f4c77426-3ec4-4532-b94d-83fff64f75c4 # Global donate
handle: ctaCustom
instructions: 'Use this if you want the link to be offsite to an external site - use full url'
name: 'CTA custom link'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
