contentColumnType: string
fieldGroup: f4c77426-3ec4-4532-b94d-83fff64f75c4
handle: ctaPosition
instructions: 'Position on top of all content or bottom'
name: 'CTA position'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Bottom
        -
          - value
          - bottom
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Top
        -
          - value
          - top
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
