columnSuffix: null
contentColumnType: boolean
fieldGroup: f4c77426-3ec4-4532-b94d-83fff64f75c4 # Global donate
handle: ctaShowSitewide
instructions: 'turn on to show this call to action on every page'
name: 'Show sitewide'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
