columnSuffix: null
contentColumnType: string
fieldGroup: 9f57329d-94c6-468b-a2cb-9620f9a80df9 # Social links
handle: defaultSocialImage
instructions: ''
name: 'Default social image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:e78a7658-fe2e-4fe3-a2de-59a0160b585e' # Social
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:e78a7658-fe2e-4fe3-a2de-59a0160b585e' # Social
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
