columnSuffix: null
contentColumnType: string
fieldGroup: a96af16e-ad03-4ad7-bc3c-5c414a28f554 # Donate 
handle: donateInfoBoxList
instructions: ''
name: 'Donate benefits item list'
searchable: false
settings:
  contentTable: '{{%matrixcontent_donateinfoboxlist}}'
  maxBlocks: '2'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
