columnSuffix: null
contentColumnType: text
fieldGroup: a96af16e-ad03-4ad7-bc3c-5c414a28f554 # Donate 
handle: donateInfoBoxMoreText
instructions: 'Use this to expand on the information. A more button will appear if you add content here. If it is empty no button will appear'
name: 'Donate info box more text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
