contentColumnType: string
fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec
handle: download
instructions: ''
name: Download
searchable: false
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add a file for download'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
