columnSuffix: null
contentColumnType: text
fieldGroup: 2d92916c-c74c-4dec-aa83-2f95c7899790 # Email newsletters
handle: emailPreviewText
instructions: ''
name: 'Email preview text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
