contentColumnType: string
fieldGroup: ac99d94b-1a00-40be-97ab-c2fce40d1100
handle: entryLink
instructions: ''
name: 'Entry link'
searchable: true
settings:
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Select an entry - thus will be a menu link to the entry content'
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
