contentColumnType: string(255)
fieldGroup: b0271536-52a9-46ee-8122-425017ee9f4d
handle: externalWebsite
instructions: 'Add any relevant external website link here '
name: 'External website'
searchable: true
settings:
  maxLength: 255
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
