contentColumnType: text
fieldGroup: b0271536-52a9-46ee-8122-425017ee9f4d
handle: externalWebsiteDescription
instructions: ''
name: 'External website description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '3'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
