columnSuffix: null
contentColumnType: string
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f # Featured
handle: featureSplitLines
instructions: ''
name: 'Feature split lines'
searchable: false
settings:
  contentTable: '{{%matrixcontent_featuresplitlines}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
