columnSuffix: null
contentColumnType: string
fieldGroup: 972163a3-4d75-4e5a-af88-88030b7a0689 # Global copyright
handle: footerLinks
instructions: ''
name: 'Footer links'
searchable: true
settings:
  contentTable: '{{%matrixcontent_footerlinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
