columnSuffix: null
contentColumnType: text
fieldGroup: e28a8bb8-82a0-4f13-a087-8b404ad4662c # Campaign
handle: formTitle
instructions: 'This replaces any form title with your own. If you leave it blank then the mailchimp form title will be used from the embedded code'
name: 'Form title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
