contentColumnType: text
fieldGroup: 6aa2582a-f09c-43e9-96bf-6287ebf48a25
handle: headingForDocuments
instructions: ''
name: 'Heading for documents'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
