columnSuffix: ciqftmyd
contentColumnType: boolean
fieldGroup: 04f271ca-91c2-45b8-a0a9-5510973cadcd # Pages
handle: hideEmailSubscribe
instructions: 'Turn this on to hide the email subscribe on the page. By default this is off and email subscribe field is shown'
name: 'Hide email subscribe'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
