contentColumnType: string
fieldGroup: e001e685-5f71-409f-88bf-0a4c333d9520
handle: image
instructions: ''
name: Image
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
