columnSuffix: null
contentColumnType: string
fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec # Banner
handle: impact
instructions: ''
name: 'Impact '
searchable: false
settings:
  contentTable: '{{%matrixcontent_impact}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
