contentColumnType: string
fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec
handle: impactStats
instructions: 'Use this to create a title and a series of cards with icons and text to illustrate statistics'
name: 'Impact stats'
searchable: false
settings:
  contentTable: '{{%matrixcontent_impactstats}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
