contentColumnType: text
fieldGroup: 6aa2582a-f09c-43e9-96bf-6287ebf48a25
handle: jobDescription
instructions: ''
name: 'Job description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
