columnSuffix: null
contentColumnType: datetime
fieldGroup: 6aa2582a-f09c-43e9-96bf-6287ebf48a25 # Jobs
handle: jobInterviewDates
instructions: 'Add the date of the week when interviews will take place - assumed week commencing from this date'
name: 'Interview dates'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
