columnSuffix: null
contentColumnType: text
fieldGroup: 6aa2582a-f09c-43e9-96bf-6287ebf48a25 # Jobs
handle: jobLocation
instructions: ''
name: 'Job location'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
