columnSuffix: null
contentColumnType: string
fieldGroup: a96af16e-ad03-4ad7-bc3c-5c414a28f554 # Donate 
handle: justgivingImage
instructions: ''
name: 'Justgiving image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
