columnSuffix: null
contentColumnType: text
fieldGroup: a96af16e-ad03-4ad7-bc3c-5c414a28f554 # Donate 
handle: justgivingSubtext
instructions: ''
name: 'Justgiving subtext'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
