columnSuffix: null
contentColumnType: string
fieldGroup: 04f271ca-91c2-45b8-a0a9-5510973cadcd # Pages
handle: linkList
instructions: ''
name: 'Link list'
searchable: false
settings:
  contentTable: '{{%matrixcontent_linklist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
