columnSuffix: ooirzavv
contentColumnType: text
fieldGroup: 04f271ca-91c2-45b8-a0a9-5510973cadcd # Pages
handle: listTitle
instructions: ''
name: 'List title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
