columnSuffix: null
contentColumnType: string
fieldGroup: e001e685-5f71-409f-88bf-0a4c333d9520 # Default
handle: locationtags
instructions: 'Choose a location to tag this content with'
name: 'Location tags'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'taggroup:b7f30b7b-5724-41e0-88ef-dc4a0135c4ca' # Location
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
