columnSuffix: null
contentColumnType: text
fieldGroup: e28a8bb8-82a0-4f13-a087-8b404ad4662c # Campaign
handle: mainTextTitle
instructions: 'Appears at the top of the body text'
name: 'Main text title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
