columnSuffix: null
contentColumnType: text
fieldGroup: 6f31baa9-2520-41f6-ab02-adf43db48203 # Global contact
handle: manchesterAddress
instructions: 'Use separate lines for address - single space line returns by holding shift return'
name: 'Manchester address'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
