columnSuffix: null
contentColumnType: text
fieldGroup: 6f31baa9-2520-41f6-ab02-adf43db48203 # Global contact
handle: manchesterTel
instructions: ''
name: 'Manchester telephone'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
