columnSuffix: wsejugdj
contentColumnType: text
fieldGroup: ac99d94b-1a00-40be-97ab-c2fce40d1100 # Menu
handle: offcanvasMenuTitle
instructions: ''
name: 'Offcanvas menu title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
