contentColumnType: string
fieldGroup: f8f993ed-1301-42d7-92b2-acb531dbe101
handle: oldNewsImage
instructions: ''
name: 'Old news image'
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:2004cf85-89b4-43cc-8c92-7cfe1ed5ebb0'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:2004cf85-89b4-43cc-8c92-7cfe1ed5ebb0'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
