columnSuffix: null
contentColumnType: text
fieldGroup: b4228c3b-a696-4b4f-8de9-0c981b63489a # Fundraising donate
handle: oneOffDonationButton
instructions: ''
name: 'One off donation button'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
