columnSuffix: null
contentColumnType: string
fieldGroup: 5bd7b2c9-de07-41a0-889c-3f0fc7ef292f # Featured
handle: partnerImage
instructions: 'If the feature is a campaign involving a partner funder or service you can add a transparent brand image for them here'
name: 'Partner image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:2297b6d5-b0fa-425f-bb4d-22b9658448ed' # Campaign images
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:2297b6d5-b0fa-425f-bb4d-22b9658448ed' # Campaign images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
