contentColumnType: string
fieldGroup: 7b4716aa-31b4-4e08-8bcb-6692c45f93cc
handle: pdfDocument
instructions: ''
name: 'PDF document'
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8b316631-f36c-481c-8e3f-c8aab26c4c24'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
