contentColumnType: string
fieldGroup: 7b4716aa-31b4-4e08-8bcb-6692c45f93cc
handle: pdfThumbnailImage
instructions: ''
name: 'PDF Thumbnail image'
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:bb3e4bc0-fa9e-4402-80c0-d188bf7f77e9'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: 'PDF thumbnails are automatically created and saved in this field'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:bb3e4bc0-fa9e-4402-80c0-d188bf7f77e9'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
