contentColumnType: string
fieldGroup: b0271536-52a9-46ee-8122-425017ee9f4d
handle: projectLogo
instructions: 'If the project has a logo upload a transparent one here'
name: 'Project logo'
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:projectImage'
  singleUploadLocationSubpath: logos
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
