contentColumnType: text
fieldGroup: b0271536-52a9-46ee-8122-425017ee9f4d
handle: projectDescription
instructions: ''
name: 'Project description'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes:
    - '7'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
