contentColumnType: string
fieldGroup: b0271536-52a9-46ee-8122-425017ee9f4d
handle: projectContent
instructions: ''
name: 'Project content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_projectcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
