columnSuffix: null
contentColumnType: datetime
fieldGroup: 7b4716aa-31b4-4e08-8bcb-6692c45f93cc # Publications
handle: publicationDate
instructions: ''
name: 'Publication date'
searchable: true
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
