columnSuffix: null
contentColumnType: text
fieldGroup: 7b4716aa-31b4-4e08-8bcb-6692c45f93cc # Publications
handle: publishersNames
instructions: ''
name: 'Publishers name(s)'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
