columnSuffix: null
contentColumnType: text
fieldGroup: e001e685-5f71-409f-88bf-0a4c333d9520 # Default
handle: quote
instructions: ''
name: Quote
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
