contentColumnType: text
fieldGroup: e001e685-5f71-409f-88bf-0a4c333d9520
handle: quoteSource
instructions: ''
name: 'Quote source'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
