columnSuffix: null
contentColumnType: string
fieldGroup: b4228c3b-a696-4b4f-8de9-0c981b63489a # Fundraising donate
handle: regularGivingAmountBoxes
instructions: ''
name: 'Regular giving amount boxes'
searchable: false
settings:
  contentTable: '{{%matrixcontent_regulargivingamountboxes}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
