contentColumnType: string
fieldGroup: b0271536-52a9-46ee-8122-425017ee9f4d
handle: relatedPublications
instructions: 'If there are publications relevant to the project then please select'
name: 'Related publications'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add related publication'
  showSiteMenu: true
  source: null
  sources:
    - 'section:0d088044-129d-459a-8873-012a51dea2bb'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
