contentColumnType: string
fieldGroup: 0d3f66ab-1780-42d8-936f-e106849c2d0f
handle: sectionRow
instructions: ''
name: 'Section row'
searchable: true
settings:
  contentTable: '{{%matrixcontent_sectionrow_3}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
