contentColumnType: text
fieldGroup: c38c46d2-bf79-4921-873b-f0ee33727fac
handle: staffRoleDescription
instructions: 'Add a small description or bio of staff here '
name: 'Staff biog'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  cleanupHtml: true
  columnType: text
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
