contentColumnType: string
fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec
handle: staffTeam
instructions: ''
name: 'Staff team'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: 'Assign staff to team'
  showSiteMenu: true
  source: 'group:8fa82dbc-e231-4473-8a94-fab2e738ce92'
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
