columnSuffix: null
contentColumnType: text
fieldGroup: f5174c3f-c106-4d5c-a957-e1df328899e9 # Global subscribe
handle: subscribeBoxSideHeading
instructions: 'This is the title of subscribe box on the side nav column'
name: 'Subscribe box side heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
