columnSuffix: null
contentColumnType: text
fieldGroup: e28a8bb8-82a0-4f13-a087-8b404ad4662c # Campaign
handle: subscribeForm
instructions: '**Important** if using a mailchimp form only copy the form from the embed code eg start copy at "<form "  and end the copy with the form closing tag "</form>'
name: 'Subscribe form'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '15'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
