columnSuffix: null
contentColumnType: text
fieldGroup: 95a13bbd-3401-43e3-84b1-479984da84ec # Banner
handle: subTitle
instructions: ''
name: 'Sub title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
