columnSuffix: null
contentColumnType: string
fieldGroup: 567108c1-b2bd-416d-ae6e-6bcc290ba4c8 # Sponsors
handle: SupporterCategory
instructions: ''
name: Category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:bc81b1bc-9a02-4ce7-948a-aa5c8bdebd32' # Supporters
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
