contentColumnType: string
fieldGroup: 567108c1-b2bd-416d-ae6e-6bcc290ba4c8
handle: supporterLogo
instructions: ''
name: 'Supporter logo'
searchable: true
settings:
  allowSelfRelations: false
  allowedKinds: null
  defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  defaultUploadLocationSubpath: supporter
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add transparent logo of support / funder'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:69530c26-670d-47c2-a35f-a3ce5489b277'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
