columnSuffix: null
contentColumnType: text
fieldGroup: e28a8bb8-82a0-4f13-a087-8b404ad4662c # Campaign
handle: video
instructions: ''
name: Video
searchable: false
settings:
  url: ''
translationKeyFormat: null
translationMethod: none
type: wrav\oembed\fields\OembedField
