columnSuffix: null
contentColumnType: text
fieldGroup: 567108c1-b2bd-416d-ae6e-6bcc290ba4c8 # Sponsors
handle: websiteUrl
instructions: ''
name: 'Website url'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
