field: 489f013c-c054-4552-b965-94911c2bae90 # Icons
fieldLayouts:
  c8fd50b6-af31-4e08-a571-7ede22167847:
    tabs:
      -
        elements:
          -
            fieldUid: b85bb62b-0b4e-42d9-a1b0-7b962a4ef491 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 363cf021-aee1-4c33-a240-4cee24ffc96a # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 08a7e56e-2483-4fe2-a651-649f8423c463 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c376e0b9-b7ff-43d9-90b3-708f9e817bf2 # Custom icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a8fb4007-f9b2-4386-8444-4c3f8e561b86 # Icon color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f55508fe-d5c8-43dc-b831-c7369df9e8f7 # Icon size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 608492a4-e765-45ee-a9f5-6ad3aeb2d1e0 # Button link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f63717c3-d525-4118-8d12-eca209c31c95 # Button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  08a7e56e-2483-4fe2-a651-649f8423c463: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      columnType: text
      iconSets:
        - 'folder:/SVG'
      remoteSets: ''
      showLabels: '1'
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
  363cf021-aee1-4c33-a240-4cee24ffc96a: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  608492a4-e765-45ee-a9f5-6ad3aeb2d1e0: # Button link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  a8fb4007-f9b2-4386-8444-4c3f8e561b86: # Icon color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: iconColor
    instructions: ''
    name: 'Icon color'
    searchable: true
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  b85bb62b-0b4e-42d9-a1b0-7b962a4ef491: # Category
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: category
    instructions: ''
    name: Category
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c376e0b9-b7ff-43d9-90b3-708f9e817bf2: # Custom icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: customIcon
    instructions: 'This will override icons chosen above. Remove it to use the font based icon'
    name: 'Custom icon'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f55508fe-d5c8-43dc-b831-c7369df9e8f7: # Icon size
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconSize
    instructions: ''
    name: 'Icon size'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 1x
            -
              - value
              - fa-1x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2x
            -
              - value
              - fa-2x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 3x
            -
              - value
              - fa-3x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 4x
            -
              - value
              - fa-4x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 5x
            -
              - value
              - fa-5x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 6x
            -
              - value
              - fa-6x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 7x
            -
              - value
              - fa-7x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 8x
            -
              - value
              - fa-8x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 9x
            -
              - value
              - fa-9x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 10x
            -
              - value
              - fa-10x
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f63717c3-d525-4118-8d12-eca209c31c95: # Button text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
