field: 4881baab-fb5a-4f28-8db5-8b0750a56b7d # Card items
fieldLayouts:
  28a812e5-512a-47e6-99d6-1eb3eb36516f:
    tabs:
      -
        elements:
          -
            fieldUid: 6c4c11ac-021e-45b3-a9e6-baa58884d18e # Card title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 18548933-6264-4903-9f75-516ace8330cc # Card image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7188fe22-f189-4e55-83bf-6d6625882a40 # Card image zoom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f93d305-4d2c-44ce-a430-19de42f60e40 # Card body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ee68d96e-771f-4baf-977c-bfc7f92db7e6 # Card button title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d27bf05b-0c8d-4ee5-ae8b-a7ee0c032cda # Card button link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4ddbcff3-fc20-403c-a1be-a24b71677cfc # Card button icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bf7afc56-e5af-42cc-bfd0-f51cd506df6c # Hide card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4ddbcff3-fc20-403c-a1be-a24b71677cfc: # Card button icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardButtonIcon
    instructions: ''
    name: 'Card button icon'
    searchable: true
    settings:
      columnType: text
      iconSets: '*'
      remoteSets: '*'
      showLabels: ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
  6c4c11ac-021e-45b3-a9e6-baa58884d18e: # Card title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: ''
    name: 'Card title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7f93d305-4d2c-44ce-a430-19de42f60e40: # Card body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardBody
    instructions: ''
    name: 'Card body'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7188fe22-f189-4e55-83bf-6d6625882a40: # Card image zoom
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageZoom
    instructions: 'You can zoom in on the focal point of the image by setting the zoom factor here'
    name: 'Card image zoom'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Zoom 1:1'
            -
              - value
              - '1'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Zoom 1.5'
            -
              - value
              - '1.5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Zoom 2.0'
            -
              - value
              - '2'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Zoom 2.5'
            -
              - value
              - '2.5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Zoom 3'
            -
              - value
              - '3'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  18548933-6264-4903-9f75-516ace8330cc: # Card image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardImage
    instructions: ''
    name: 'Card image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:65b046c4-d946-472f-9eb0-5c845aabedda' # Landing pages
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:69530c26-670d-47c2-a35f-a3ce5489b277' # Images
        - 'volume:e64ccb15-e61c-41a3-84f8-e9c3a375a142' # Unsplash images
        - 'volume:65b046c4-d946-472f-9eb0-5c845aabedda' # Landing pages
        - 'volume:3dcd4130-a19f-4afe-b979-339b59e9558d' # Events
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bf7afc56-e5af-42cc-bfd0-f51cd506df6c: # Hide card
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hideCard
    instructions: 'Turn this switch on to hide a specific card'
    name: 'Hide card'
    searchable: true
    settings:
      default: false
      offLabel: 'Show card'
      onLabel: 'Hide card'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  d27bf05b-0c8d-4ee5-ae8b-a7ee0c032cda: # Card button link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardButtonLink
    instructions: ''
    name: 'Card button link'
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  ee68d96e-771f-4baf-977c-bfc7f92db7e6: # Card button title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardButtonTitle
    instructions: ''
    name: 'Card button title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
