field: be2d090c-b7de-43dc-915b-194dc8de3e34 # Impact card
fieldLayouts:
  2a451c98-26b5-45b6-bddd-59ace9e12bcc:
    tabs:
      -
        elements:
          -
            fieldUid: bf1ee760-333d-462e-a0ad-1a014c2c9538 # Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 06085e59-ce31-4870-a7e3-e32b6f3aad17 # Stat
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 09dce948-15fb-4b5d-818c-a1e33e6cdb15 # Statistic type
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9c8ca7e8-254f-441a-8bc8-6b48a21039eb # Impact text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9c8ca7e8-254f-441a-8bc8-6b48a21039eb: # Impact text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: impactText
    instructions: 'Add a short description that goes beneath the stat to give meaning and context to the number - if no number then a brief paragraph will do. '
    name: 'Impact text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  09dce948-15fb-4b5d-818c-a1e33e6cdb15: # Statistic type
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: statisticType
    instructions: 'Add a heading category name for this statistic. Eg is it about mental health, Outreach, Housing etc?'
    name: 'Statistic type'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  06085e59-ce31-4870-a7e3-e32b6f3aad17: # Stat
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stat
    instructions: 'Add the number of the statistic here'
    name: Stat
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bf1ee760-333d-462e-a0ad-1a014c2c9538: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      columnType: text
      iconSets:
        - 'folder:/SVG'
      remoteSets: ''
      showLabels: '1'
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
