field: 62cc6b1f-04f6-4075-8e6c-eea573ce8d0b # Split Line
fieldLayouts:
  c9ba93ae-798f-42b5-8d14-b4d9399d5cbe:
    tabs:
      -
        elements:
          -
            fieldUid: c3f477ac-a06f-4005-a615-f02d7f61475c # Line
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c3f477ac-a06f-4005-a615-f02d7f61475c: # Line
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: line
    instructions: ''
    name: Line
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
