field: 7f9319ae-1f11-46d3-9583-bc10fba15291 # Stat
fieldLayouts:
  6be33631-1221-4350-86a5-e59905fedb2c:
    tabs:
      -
        elements:
          -
            fieldUid: f6eb9d8b-9521-4dcc-abbe-2ca820acd962 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 291ce790-b12a-4a1f-8dc5-28adcc651ae9 # text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b70052cf-a8da-4fdd-8bc3-e283d5a27d1e # Icon color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 903170fb-f831-4048-85fd-6b7f31cd2dff # Icon size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  291ce790-b12a-4a1f-8dc5-28adcc651ae9: # text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  903170fb-f831-4048-85fd-6b7f31cd2dff: # Icon size
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconSize
    instructions: ''
    name: 'Icon size'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 1x
            -
              - value
              - fa-1x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 2X
            -
              - value
              - fa-2x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 3x
            -
              - value
              - fa-3x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 4x
            -
              - value
              - fa-4x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 5x
            -
              - value
              - fa-5x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 6x
            -
              - value
              - fa-6x
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 7x
            -
              - value
              - fa-7x
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b70052cf-a8da-4fdd-8bc3-e283d5a27d1e: # Icon color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: iconColor
    instructions: ''
    name: 'Icon color'
    searchable: false
    settings:
      defaultColor: '#ffffff'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  f6eb9d8b-9521-4dcc-abbe-2ca820acd962: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      columnType: text
      iconSets:
        - 'folder:/SVG'
      remoteSets: ''
      showLabels: ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
