field: af60db8b-ccbf-4192-9a5c-fc0639d3899d
fieldLayouts:
  65b235da-53d1-4f0b-b743-f767ef3358a4:
    tabs:
      -
        fields:
          e0e8bec7-1b0f-4f37-94fb-9cb74fd433a3:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  e0e8bec7-1b0f-4f37-94fb-9cb74fd433a3:
    contentColumnType: text
    fieldGroup: null
    handle: tickItem
    instructions: ''
    name: 'Tick item'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
