field: 2e9995c0-eaab-4dbc-b6d0-1a5b92d5e7b2
fieldLayouts:
  3685dd56-cfab-49ff-9caa-1c9deebec204:
    tabs:
      -
        elements:
          -
            fieldUid: ca158746-21d0-492a-848b-8165c4a69b2f
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07f10331-5743-426a-b68c-5150c2e37921
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b3e391ba-03c4-4001-90be-acf672dcc7e9
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b7361645-8d0c-4836-8cc3-e91a8c78d0ab
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  07f10331-5743-426a-b68c-5150c2e37921:
    contentColumnType: text
    fieldGroup: null
    handle: stat
    instructions: 'Add the number of the statistic here - if there is no number leave blank (looks better with)'
    name: Stat
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b3e391ba-03c4-4001-90be-acf672dcc7e9:
    contentColumnType: text
    fieldGroup: null
    handle: statisticType
    instructions: 'Add a heading category name for this statistic. Eg is it about mental health, Outreach, Housing etc?'
    name: 'Statistic type'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b7361645-8d0c-4836-8cc3-e91a8c78d0ab:
    contentColumnType: text
    fieldGroup: null
    handle: impactText
    instructions: 'Add a short description that goes beneath the stat to give meaning and context to the number - if no number then a brief paragraph will do. '
    name: 'Impact text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ca158746-21d0-492a-848b-8165c4a69b2f:
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      columnType: text
      iconSets:
        - 'font:fa-brands-400.woff2'
        - 'font:fa-regular-400.woff'
        - 'font:fa-solid-900.woff'
        - 'font:themify--fvbane.ttf'
      remoteSets: ''
      showLabels: ''
    translationKeyFormat: null
    translationMethod: none
    type: verbb\iconpicker\fields\IconPickerField
