field: 9155dd04-124d-4208-8d10-9f83d944870e
fieldLayouts:
  bffbcb67-1f5a-49c1-a883-950caf0a66f0:
    tabs:
      -
        fields:
          675b889f-8f75-4714-9b69-050cf6339d83:
            required: false
            sortOrder: 2
          cf23b0ca-dd3c-43c3-882c-a13cb6753156:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  675b889f-8f75-4714-9b69-050cf6339d83:
    contentColumnType: string(255)
    fieldGroup: null
    handle: customLink
    instructions: ''
    name: 'Custom link'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  cf23b0ca-dd3c-43c3-882c-a13cb6753156:
    contentColumnType: text
    fieldGroup: null
    handle: customLinkTitle
    instructions: ''
    name: 'Custom link title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
