field: 388aac61-d66c-4310-b77f-3c208ae044d2 # Quote
fieldLayouts:
  c0b9ed0b-67af-4f48-8b3e-5d25b44e52e9:
    tabs:
      -
        elements:
          -
            fieldUid: 30d37422-65da-4834-9c34-09dfa288b27a # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b3bb00b6-db87-423a-81f0-8d1197a68b96 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f00d7e3-9605-49bb-bdbe-f2d330b29afd # Citation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f00d7e3-9605-49bb-bdbe-f2d330b29afd: # Citation
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: citation
    instructions: ''
    name: Citation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  30d37422-65da-4834-9c34-09dfa288b27a: # Quote
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b3bb00b6-db87-423a-81f0-8d1197a68b96: # Source
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: source
    instructions: ''
    name: Source
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
