field: 58e6b000-f6fa-4f8e-b3b7-fb3c49c5159c # Amount box
fieldLayouts:
  a60878f9-8656-464b-a43e-0d5c7de26090:
    tabs:
      -
        elements:
          -
            fieldUid: 9e96b439-8999-4bec-9e4d-dd45d1c62ee0 # Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a36e8e45-94b4-44f3-8a50-fedca2809c87 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dc8a3ad4-ee07-4f09-9300-5e4149852824 # Button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9e96b439-8999-4bec-9e4d-dd45d1c62ee0: # Amount
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: amount
    instructions: ''
    name: Amount
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a36e8e45-94b4-44f3-8a50-fedca2809c87: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dc8a3ad4-ee07-4f09-9300-5e4149852824: # Button text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
