field: 87854a77-5940-4f76-aad3-2348b85aeb55 # Steps
fieldLayouts:
  3d1e0946-6aac-4259-9665-b4e1b414b2da:
    tabs:
      -
        elements:
          -
            fieldUid: a0273f4c-1e9a-4678-9226-1dadcfb87bf2 # Step no
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5ea8f6a0-b15a-47b0-b520-ad611adb946f # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c4d9d5fd-801e-4c89-a1a1-99208d4d455e # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5ea8f6a0-b15a-47b0-b520-ad611adb946f: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a0273f4c-1e9a-4678-9226-1dadcfb87bf2: # Step no
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stepNo
    instructions: ''
    name: 'Step no'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c4d9d5fd-801e-4c89-a1a1-99208d4d455e: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
