field: aa0b3f5c-1cfd-46e3-9931-ca6a57389a3d # List of links
fieldLayouts:
  143ae58c-7f42-42a0-8662-c573af0b5a97:
    tabs:
      -
        elements:
          -
            fieldUid: 8d45c34a-4ae4-486a-8399-b682f0c39024 # Link title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ceb17f58-efdd-4d30-b388-fa11f686a06e # Link description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 572fbe02-d7d9-4973-951a-8d51671450c2 # Link url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8d45c34a-4ae4-486a-8399-b682f0c39024: # Link title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkTitle
    instructions: ''
    name: 'Link title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  572fbe02-d7d9-4973-951a-8d51671450c2: # Link url
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'Link url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  ceb17f58-efdd-4d30-b388-fa11f686a06e: # Link description
    columnSuffix: xphonawg
    contentColumnType: text
    fieldGroup: null
    handle: linkDescription
    instructions: ''
    name: 'Link description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
