fieldLayouts:
  d9f22edb-e1d7-4a49-b7e2-b903b628cf11:
    tabs:
      -
        elements:
          -
            fieldUid: e96f447b-ed39-42f1-aa27-a7e77bb9444c # Show sitewide
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb4dd8d4-526e-45bc-9df9-1798512dd7be # CTA section bg color
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 88f481ab-083c-4016-a3a2-1ce22e2f1a55 # CTA text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4e8c561e-1c2e-4518-ba84-7409f32efe43 # CTA text short version
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c37dd07c-e401-4016-a7c9-bbfd7f66055a # CTA link
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0089a26-45cd-4af0-a9f2-5f78694a585c # CTA custom link
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 854a81d0-40bc-45ae-ae97-3405888619f2 # CTA button color
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b94541a5-4fee-46e9-8f0d-59da799180c8 # CTA button text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f1b70a7-c93d-4d55-bc43-80124c28d43d # CTA position
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Call to action'
        sortOrder: 1
handle: callsToAction
name: 'Calls to action'
sortOrder: 1
