fieldLayouts:
  b9db6198-dddf-4cc3-ad21-f3d5ada72d3b:
    tabs:
      -
        fields:
          1c311a44-27b4-4019-9baa-1bb97fa26364:
            required: false
            sortOrder: 2
          635203ec-4f05-48bf-87b9-bae85a832e4a:
            required: false
            sortOrder: 4
          a8866897-a11c-4d44-bbca-2997e4ab9b0c:
            required: false
            sortOrder: 1
          c9ad087d-6e04-43ed-af26-d691dd15c832:
            required: false
            sortOrder: 3
          fc7f6dca-b865-4fbf-a104-9d7c98187746:
            required: false
            sortOrder: 5
        name: 'Footer links & copyright'
        sortOrder: 1
handle: footer
name: Footer
