fieldLayouts:
  d8c73f87-6f84-4a27-bab5-4913319d64b5:
    tabs:
      -
        elements:
          -
            fieldUid: daf32c17-29eb-4fa9-88fd-b0e569f8cbfc # Organisation name
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 49f44432-4e22-4832-87b3-1e0741da1e5c # Brighton address
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0caf91e5-c05d-4f17-944b-888b7ab7a3bf # Manchester address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: bb7da2af-04eb-40d1-84a4-9e7e38a0bcbe # Brighton email
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: efa4f938-e59f-45fa-9595-c6ac86d87575 # Manchester email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 51792261-a438-4fc7-9604-1581089a917e # Brighton telephone
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: ff99de02-72ff-47a4-905e-45a229af6bdc # Manchester telephone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 635203ec-4f05-48bf-87b9-bae85a832e4a # Charity organisation statement
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 608f5ec4-9c1d-4bfc-bf3d-9b4c81edab7a # Additional contact info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global contact'
        sortOrder: 1
handle: organisationInfo
name: 'Organisation info'
sortOrder: 5
