fieldLayouts:
  d8c73f87-6f84-4a27-bab5-4913319d64b5:
    tabs:
      -
        fields:
          49f44432-4e22-4832-87b3-1e0741da1e5c:
            required: false
            sortOrder: 2
          51792261-a438-4fc7-9604-1581089a917e:
            required: false
            sortOrder: 4
          bb7da2af-04eb-40d1-84a4-9e7e38a0bcbe:
            required: false
            sortOrder: 3
          daf32c17-29eb-4fa9-88fd-b0e569f8cbfc:
            required: false
            sortOrder: 1
        name: 'Global contact'
        sortOrder: 1
handle: organisationInfo
name: 'Organisation info'
