fieldLayouts:
  7369ccfc-3a2d-48e2-9ffb-73ef60ea5448:
    tabs:
      -
        fields:
          4da40367-5b18-49c8-90d8-9f0d6525d39a:
            required: false
            sortOrder: 2
          b73a5e64-5d5e-41a7-853a-824a3024080d:
            required: false
            sortOrder: 1
          b7bc05a6-852e-4098-94e2-a61eeab3c504:
            required: false
            sortOrder: 3
          d8dee4b7-c8da-42e3-aaca-bf3d942c6092:
            required: false
            sortOrder: 4
        name: 'Global site info'
        sortOrder: 1
handle: siteInfo
name: 'Site info'
