fieldLayouts:
  7369ccfc-3a2d-48e2-9ffb-73ef60ea5448:
    tabs:
      -
        elements:
          -
            fieldUid: b73a5e64-5d5e-41a7-853a-824a3024080d # Page not found
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4da40367-5b18-49c8-90d8-9f0d6525d39a # Show cookie info
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b7bc05a6-852e-4098-94e2-a61eeab3c504 # Cookie type
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d8dee4b7-c8da-42e3-aaca-bf3d942c6092 # Cookie message
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a6e31799-dc1a-4bd7-a76f-d4ae0c4d8a28 # Cookie decline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 861c1d6a-b282-498a-82e8-58a6a4630696 # Cookie dismiss
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c2c6a62d-e8e4-4664-aca3-611d3a47e5aa # Cookie page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 535d84be-7ee8-4862-a036-1a469858e372 # Cookie Policy Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Global site info'
        sortOrder: 1
handle: siteInfo
name: 'Site info'
sortOrder: 6
