fieldLayouts:
  eacc505c-b246-4d4b-a4eb-3db3ab541e7a:
    tabs:
      -
        fields:
          37e9d741-d6ef-4993-91a6-4c4750d02b84:
            required: false
            sortOrder: 1
          3ef67368-ca08-4344-8bab-3a731b6645a6:
            required: false
            sortOrder: 3
          75fd46e7-4a10-4b5a-adc0-77629e5ebeef:
            required: false
            sortOrder: 5
          c4c6df1b-832c-4689-8915-e0b4e6de1d7b:
            required: false
            sortOrder: 4
          d60f1d78-3ea1-4eff-a47f-9fb746e6f9cf:
            required: false
            sortOrder: 2
        name: 'Social links'
        sortOrder: 1
handle: social
name: Social
