fieldLayouts:
  eacc505c-b246-4d4b-a4eb-3db3ab541e7a:
    tabs:
      -
        elements:
          -
            fieldUid: 37e9d741-d6ef-4993-91a6-4c4750d02b84 # Facebook
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d60f1d78-3ea1-4eff-a47f-9fb746e6f9cf # YouTube
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ef67368-ca08-4344-8bab-3a731b6645a6 # Instagram
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c4c6df1b-832c-4689-8915-e0b4e6de1d7b # LinkedIn
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 75fd46e7-4a10-4b5a-adc0-77629e5ebeef # Twitter
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social links'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 09357de5-17bb-432c-a503-7d727f1bdd26 # Default social image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e461ef45-da6a-4ec5-902b-32d43e622ea7 # Twitter card large
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: aa683a3d-e696-4566-a913-c8413511577f # Twitter thumb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: baff16ba-92ba-4863-8ad4-46a68f8787d6 # Facebook post image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Social images'
        sortOrder: 2
handle: social
name: 'Global Social'
sortOrder: 4
