fieldLayouts:
  e14a883e-4671-45af-82bc-8df5fd7549fc:
    tabs:
      -
        fields:
          03c5550e-dcc7-4568-bc0d-fffc089f9396:
            required: false
            sortOrder: 1
        name: 'Tracking scripts'
        sortOrder: 1
handle: tracking
name: Tracking
