defaultPlacement: end
enableVersioning: true
handle: campaigns
name: Campaigns
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    enabledByDefault: true
    hasUrls: true
    template: campaigns/_entry
    uriFormat: '{% if object.level == 1 %}campaigns/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 052b2d79-6fd3-41e3-b711-f78d48bfded1
type: structure
