enableVersioning: true
handle: emailNewsletters
name: 'Email Newsletters'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    enabledByDefault: true
    hasUrls: true
    template: email-newsletters/_entry
    uriFormat: 'email-newsletters/{slug}'
type: channel
