defaultPlacement: end
enableVersioning: true
handle: eventBrite
name: 'Event brite'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    enabledByDefault: true
    hasUrls: true
    template: events/index.twig
    uriFormat: events
type: single
