enableVersioning: true
handle: events
name: Events
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    enabledByDefault: true
    hasUrls: true
    template: events/_entry
    uriFormat: 'events/{slug}'
type: channel
