enableVersioning: true
handle: fundraising
name: 'Fundraising pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: 'get-involved/{slug}'
structure:
  maxLevels: null
  uid: de86f1c1-5ce8-431e-a5b4-010429efe06f
type: structure
