enableVersioning: true
handle: mainMenu
name: 'Main menu'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: b01af136-7047-41af-8510-c449f4698736
type: structure
