enableVersioning: true
handle: miscPages
name: 'Misc pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
type: channel
