defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: adffd4ad-03a0-45f7-81c2-2e075b6c72fe
type: structure
