defaultPlacement: end
enableVersioning: true
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'our-work/{locationtags.one().slug}/{slug}'
structure:
  maxLevels: null
  uid: ca5441da-ff54-4de4-a0ec-86d9f8a42288
type: structure
