enableVersioning: true
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a:
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: '{% if object.level == 1 %}our-work/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: ca5441da-ff54-4de4-a0ec-86d9f8a42288
type: structure
