defaultPlacement: end
enableVersioning: true
handle: publications
name: Publications
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    enabledByDefault: true
    hasUrls: true
    template: publications/_entry
    uriFormat: '{% if object.level == 1 %}our-work/{% if object.type == ''research''%}research-and-policy{%else%}{type}{% endif %}/{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: e9c5933d-10f2-4194-984c-c6ca2f3731b9
type: structure
