defaultPlacement: end
enableVersioning: true
handle: topNav
name: 'Top nav'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  dda3b550-c778-4d47-86b0-11543ac8053a: # Justlife
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 47a243fd-78bc-4d32-bcb5-9619050789bf
type: structure
